### ISSUE TITLE
Basic supported configuration item types

### ISSUE THREAD

**Issue by cvarjao** [bcgov/dcts#10]
Base on [Configuration item](https://en.wikipedia.org/wiki/Configuration_item) wikipedia entry:

- Hardware
  - Server (Physical, Virtual, Cluster, "Stream")
  - Router/Proxy
- Software
  - Application
  - Web Services
  - Composite Applications
  - COTS
  - Components (e.g.: CRON tasks)
  - DataSet (e.g.: Oracle Schema)
- Credentials
   - Username + password
   - Key/License/Password
- Communications/Networks
   - Network connection
   - Firewall Rule
- Location
   - Data Center
   - Zone
- People (Staff and Contractors, Organization unit)

**Comment by swcurran** [comment]
Closing this for now. Much work has gone into evolving the data model for the database, and work continues.  Including all of these are an eventual target, but we are not currently working on this right now.
