### ISSUE TITLE
Manage technology and roadmap

### ISSUE THREAD

**Issue by cvarjao** [bcgov/dcts#11]
We need to know that an application uses specific technology (e.g.: Java 1.7, Java 1.8, Oracle 11G, Oracle 12C, Oracle Instant Client 12c, .Net 4, ...)

Technologies have a end-of-life (de-support) date, and we need to keep track so we are not using technologies that are no longer supported.

Discussion point: Should we import build dependencies? e.g.: ojdbc 12, spring 4, Hibernate 4.2, struts, ...

**Comment by swcurran** [comment]
Closing this for now.  This is a capability for the target result, but not being worked on right now.
