### ISSUE TITLE
Secure Credential/Secret storage and management

### ISSUE THREAD

**Issue by cvarjao** [bcgov/dcts#12]
Credentials and secrets MUST be handled with extreme care to guarantee it always secure and kept confidential.
Perhaps the credentials/secrets itself may be stored in a specialized scripted database/service (e..g: vault, password manager pro, ...)

**Comment by swcurran** [comment]
Closing this for now. It's not clear that credentials will embedded within this solution or just referenced and handled within a separate mechanism. Regardless, this is a longer term goal, and not part of the current work.
