### ISSUE TITLE
Define a bundle for a component that can be loaded into the CMDB

### ISSUE THREAD

**Issue by swcurran** [bcgov/dcts#33]
In the latest iterations, the data for loading in the schema has been literal - code in the form of OrientDB load statements to create Nodes and Edges according to the defined CMDB data model.  More useful would be a more concise representation that can be passed to an API endpoint for loading via transformation and generation.

The bundle definition will be collaboratively and iteratively defined in the [wiki here](https://github.com/bcgov/nrs-cmdb/wiki/Bundle-Definition).

* Literal hardware, software nodes and fixed edges between those nodes
* Requires and Provides endpoints for external connections from the nodes
* Environments into which the literal nodes/edges can be materialized

**Comment by GeorgeWalker** [comment]
Completed - demonstrated to Clecio
