### ISSUE TITLE
Implement an API endpoint and logic to load a bundle

### ISSUE THREAD

**Issue by swcurran** [bcgov/dcts#34]
Given the [definition of a bundle](https://github.com/bcgov/nrs-cmdb/wiki/Bundle-Definition), implement an API endpoint and logic to load such a bundle into the CMDB database.

Assume that the database has existing components.  The logic of the bundle processing should be as follows:

* Instantiate the literal software/hardware/provides/requires components and connections between them. These will eventually be nodes and edges in the database, but not immediately.
* For each environment:
  * generate and upsert into the CMDB an instance of each of node and edge defined in the previous step.
  * search the current contents of the database for the "provides" node that "best satisfies" each "requires" and create an edge between the two nodes
     * For the initial implementation, "best satisfies" can be an exact match, but assume that the implementation of the "best satisfies" will iteratively evolve over time

TDB about "requires" and "provides":

* Should an unsatisfied "requires" result in an error or a warning?
  * If it is an error, we may get into load order issues, especially if there is cycle between components.  Are cycles possible or would the configuration just be invalid?
* Related issue (that is irrelevant if cycles are not possible): On loading, when a new "provides" is loaded, should a search be done for an unsatisfied "requires" that is satisfied by the "provides".

**Comment by swcurran** [comment]
@cvarjao - Does that definition match what you are thinking?

On the instantiation of each set of nodes/edges per environment, I would think there needs to be some convention on naming (e.g. prefix).  Are you including that?

The bundle needs to support attributes that can be used later in both the "best satisfies" processing and (I assume) for the component configuration file generation.

I'm not clear how differences between environments are or should be handled.  For example, if Dev is an instance of a Web Server, but production is a cluster of load balanced web server instances.  Would that just be two similar bundles?

**Comment by GeorgeWalker** [comment]
Completed - demonstrated with Clecio
