### ISSUE TITLE
Technical Spike: Using the Sailsjs Framework with OrientDB

### ISSUE THREAD

**Issue by swcurran** [bcgov/dcts#6]
Look at what is available for this setup.  Is this a recommended platform to build upon?

Sailjs.com uses waterline for it's ORM, and waterline is capable of integrating with a variety of persistence engines - Mongo, relational, etc.  Is OrientDB a good choice in that stack?

Waterline - https://github.com/balderdashy/waterline

**Comment by GeorgeWalker** [comment]
Node.js native binary driver for OrientDB:  https://github.com/orientechnologies/orientjs

**Comment by GeorgeWalker** [comment]
At our project meeting 2017-7-27 it was decided to focus on Java
